config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controller: {
    confirmations: 'confirmations'
  }
  get 'welcome/index'

  resources :articles

  root 'welcome#index'
end

app/models/ability.rb
# frozen_string_literal: true

class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
      user ||= User.new # guest user (not logged in)
      if user.admin?
        can :manage, :all
      else
        can :read, :all
      end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  validates :title, presence: true,
                    length: { minimum: 5 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :load_user, only: [:show, :update, :destroy]
  before_action :authenticate_user!

  def index
    @articles = Article.all
  end

  def show
  end

  def new
    @article = Article.new
  end

  def edit
    @article = Article.find(params[:id])
  end

  def create
    @article = Article.new(article_params)

    if @article.save
      redirect_to @article
    else
      render 'new'
    end
  end

  def update
    if @article.update(article_params)
      redirect_to @article
    else
      render 'edit'
    end
  end

  def destroy
    @article.destroy

    redirect_to articles_path
  end

  private
  def article_params
    params.require(:article).permit(:title, :text)
  end

  def load_user
    @article = Article.find_by(id: params[:id])
  end
end

app/controllers/confirmations_controller.rb
class ConfirmationsController < Devise::ConfirmationsController
  private

  def after_confirmation_path_for(resource_name, resource)
    sign_in(resource)
    articles_path
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/articles/_form.html.erb
<%= form_with model: @article, local: true do |form| %>

  <% if @article.errors.any? %>
    <div id="error_explanation">
      <div class="alert alert-danger">
        <strong>
        <%= pluralize(@article.errors.count, "error") %> prohibited
        this article from being saved:
        </strong>
      </div>
      <ul>
        <% @article.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :title %><br>
    <%= form.text_field :title, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :text %><br>
    <%= form.text_area :text, class: "form-control"  %>
  </div>

  <div>
    <%= form.submit 'Save Article', class: 'btn btn-primary' %>
    <%= link_to('Cancel', back_path, class: 'btn btn-outline-secondary ml-2') %>
  </div>

<% end %>

app/views/articles/edit.html.erb
<div class="mx-auto mt-5" style="width: 600px;">
  <h1>Edit article</h1>

  <%= render partial: 'form', locals: { back_path: article_path(@article) } %>
</div>

app/views/articles/index.html.erb
<div class="mx-auto mt-5">
  <h1>Listing Articles</h1>

  <% if can? :create, @article %>
    <div class="float-right">
      <%= link_to('New Article', new_article_path, class: "btn btn-outline-primary mb-3 btn-lg") %>
    </div>
  <% end %>

  <table class="table text-center">
    <thead class="thead-dark">
      <tr>
        <th scope="col">ID</th>
        <th scope="col">Title</th>
        <th scope="col">Text</th>
        <th scope="col">Actions</th>
      </tr>
    </thead>
    <tbody>
      <% @articles.each do |article| %>
        <td><%= article.id %></td>
        <td><%= article.title %></td>
        <td><%= article.text %></td>
        <td>
          <%= link_to(article_path(article), class: "btn btn-outline-success") do %>
            <i class="fa fa-eye" aria-hidden="true"></i> <%= 'Show' %>
          <% end %>
          <%= link_to(edit_article_path(article), class: "btn btn-outline-warning") do %>
            <i class="fa fa-ellipsis-h" aria-hidden="true"></i> <%= 'Edit' %>
          <% end %>
          <% if can? :manage, @article %>
            <%= link_to article_path(article), class: 'btn btn-outline-danger', method: :delete, data: { confirm: 'Are you sure?' } do %>
            <i class="fa fa-trash" aria-hidden="true"></i> <%= 'Delete' %>
            <% end %>
          <% end %>
        </td>
      <% end %>
  </tbody>
  </table>

  <div class="float-right">
    <%= link_to(root_path, class: "btn btn-outline-secondary ml-2 btn-sm") do %>
      <i class="fa fa-arrow-left" aria-hidden="true"></i> <%= 'Back' %>
    <% end %>
  </div>
</div>

app/views/articles/new.html.erb
<div class="mx-auto mt-5" style="width: 600px;">
  <h1>New Article</h1>

  <%= render partial: 'form', locals: { back_path: articles_path } %>
</div>

app/views/articles/show.html.erb
<div class="mx-auto mt-5" style="width: 600px;">
  <div>
    <h3><%= @article.title %></h3>
  </div>
  <div>
    <strong>Text:</strong>
    <%= @article.text %>
  </div>
  <div class="mt-3">
    <%= link_to('Edit', edit_article_path(@article), class: 'btn btn-outline-warning btn-sm') %>
    <%= link_to(articles_path, class: "btn btn-outline-secondary ml-2 btn-sm") do %>
      <i class="fa fa-arrow-left" aria-hidden="true"></i> <%= 'Back' %>
    <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Railscast</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render partial: 'shared/navbar' %>
    <div class="container">
      <%= render partial: 'shared/flash_messages' %>
      <%= yield %>
    </div>
  </body>
  <script type="text/javascript">
    $(".alert-success" ).fadeOut(2500);
  </script>
</html>

app/views/shared/_flash_messages.html.erb
<% flash.each do |type, msg| %>
  <% if type == 'alert' %>
    <p class="alert alert-danger mt-3"><%= msg %></p>
  <% elsif type == 'notice' %>
    <p class="alert alert-success mt-3"><%= msg %></p>
  <% else %>
    <p><%= type %>: <%= msg %></p>
  <% end %>
<% end %>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <%= link_to "MY PAGE", root_path, class: 'navbar-brand' %>
  <% if user_signed_in? %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <%= link_to "Articles", articles_path, class: "nav-link" %>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Dropdown
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="#">Action</a>
          <a class="dropdown-item" href="#">Another action</a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="#">Something else here</a>
        </div>
      </li>
      <li class="nav-item">
        <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
      </li>
    </ul>
    <% end %>
    <ul class="navbar-nav ml-auto">
      <% if user_signed_in? %>
        <li class="nav-item mr-2">
          <%= link_to current_user.email, edit_user_registration_path, class: 'btn btn-outline-success' %>
        </li>
        <li class="nav-item">
          <%= link_to "Sign out", destroy_user_session_path, class: 'btn btn-outline-danger', method: :delete %>
        </li>
      <% else %>
        <li class="nav-item mr-sm-2">
          <%= link_to "Sign up", new_user_registration_path, class: 'btn btn-outline-primary' %>
        </li>
        <li class="nav-item my-2 my-sm-0">
          <%= link_to "Sign in", new_user_session_path, class: 'btn btn-primary' %>
        </li>
      <% end %>
    </ul>
  </div>
</nav>

app/views/welcome/index.html.erb
<div class="mx-auto text-center" style="width: 500px; margin-top: 15em">
  <h1 class="cover-heading">Helloo, This is my page</h1>
  <div>
    <p class="lead">Cover is a one-page template for building simple and beautiful home pages. Download, edit the text, and add your own fullscreen background photo to make it your own.</p>
    <%= link_to("Let's go", articles_path, class: "btn btn-primary btn-lg") %>
  </div>
</div>